import {evaluate} from './core.mjs';
import {fixtures} from './fixtures.mjs';
import {$,cell,metrics,status,download} from './ui.mjs';
let result=null;
for(const item of fixtures){const option=document.createElement('option');option.value=item.id;option.textContent=item.id;$('case').append(option);}
function selected(){return fixtures.find(item=>item.id===$('case').value);}
function run(){result=null;$('download').disabled=true;try{const item=selected(),baseline=evaluate($('baseline').value,item.checks),candidate=evaluate($('candidate').value,item.checks);const baselinePass=baseline.every(c=>c.passed),candidatePass=candidate.every(c=>c.passed);result={caseId:item.id,baselinePass,candidatePass,regression:baselinePass&&!candidatePass,checks:item.checks,baseline,candidate};metrics([[candidate.filter(c=>c.passed).length,'candidate checks pass'],[candidate.filter(c=>!c.passed).length,'candidate checks fail'],[result.regression?'YES':'NO','case regression']]);$('checks').replaceChildren();item.checks.forEach((check,i)=>{const tr=document.createElement('tr');cell(tr,check.type+(Object.hasOwn(check,'path')?` @ ${check.path||'(root)'}`:''));cell(tr,baseline[i].passed?'PASS':'FAIL',baseline[i].passed?'pass':'fail');cell(tr,candidate[i].passed?'PASS':'FAIL',candidate[i].passed?'pass':'fail');cell(tr,candidate[i].detail);$('checks').append(tr);});status(result.regression?'Regression: the baseline passed this case; the candidate fails.':candidatePass?'All candidate checks pass.':'Candidate fails; baseline also failed this case.',!candidatePass);$('download').disabled=false;}catch(e){status(e.message,true);}}
function restore(){const item=selected();$('prompt').textContent=item.prompt;$('baseline').value=item.baseline;$('candidate').value=item.candidate;$('contract').textContent=JSON.stringify(item.checks,null,2);run();}
$('case').addEventListener('change',restore);$('run').addEventListener('click',run);$('restore').addEventListener('click',restore);$('copy-baseline').addEventListener('click',()=>{$('candidate').value=$('baseline').value;run();});$('download').addEventListener('click',()=>{if(result)download(result,'evaldeck-checks.json');});for(const id of ['baseline','candidate'])$(id).addEventListener('input',()=>{result=null;$('download').disabled=true;status('Answers changed. Check again to update the result.');});restore();
